apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresdb
spec:
  selector:
    matchLabels:
      app: postgresdb
  serviceName: postgresdb
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: database
        image: postgres:latest
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: petclinic-configmap
        - secretRef:
            name: petclinic-secret